[profile.default]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
    "@foundry-devops/=lib/foundry-devops/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-optionssrc = "src"
out = "out"
libs = ["lib"]
